### ISSUE TITLE
always true condition leading to assert(0)

### ISSUE THREAD

**Issue by artkond** [lexfo/rpc2socks#1]
Hey guys! Awesome tool you got here. I had the server asserting zero every connect so I started looking down the code and it seems you have an always fail condition in socks_proxy.cpp. Packet size is checked to be both less than 10 and >=10 at the same time. This is always true and gets to `assert(0)`.

```cpp
bool socks_proxy::handle_socks_request__needcmd(
    client_t& client,
    const socks_packet_t& request)
/* ... */
if (packet.size() < 10){
   assert(0);
}
...

        case socks_addr_ipv4:
            if (packet.size() >= required_min_len)
            {
                assert(0);
                reply_code = socks_reply_general_failure;
                goto __send_status;
            }

```

**Comment by loxfo** [comment]
Thanks for the nice feedback and for spotting the issue! :)
